services:
  - type: web
    name: ara-mahi-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.api:app --bind 0.0.0.0:\

  - type: cron
    name: ara-mahi-refresh-jobs
    region: oregon
    schedule: "0 */6 * * *"   # Every 6 hours
    command: python src/jobs/load_jobs_all.py
